source 'https://rubygems.org'

gem 'rails', github: 'rails/rails'
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'capistrano-rails', group: :development
gem 'bower-rails', '~> 0.9.2'
gem 'pry', group: [:development, :test]
